/** Plantilla fija del servicio Monorriel (puestos + personal base AM/PM) */
window.RFS_MONORRIEL = {
  posts: [
    { id: "m01", no: 1, location: "Estación 01", position: "Ascensor" },
    { id: "m02", no: 2, location: "Estación 01", position: "Escalera" },
    { id: "m03", no: 3, location: "Estación 02", position: "Ascensor" },
    { id: "m04", no: 4, location: "Estación 02", position: "Escalera" },
    { id: "m05", no: 5, location: "Estación 03", position: "Ascensor" },
    { id: "m06", no: 6, location: "Estación 03", position: "Escalera" },
    { id: "m07", no: 7, location: "Estación 03 / Área", position: "Contenedores / Ponche" },
    { id: "m08", no: 8, location: "Estación 04", position: "Ascensor" },
    { id: "m09", no: 9, location: "Estación 04", position: "Escalera" },
    { id: "m10", no: 10, location: "Estación 05", position: "Escalera" },
    { id: "m11", no: 11, location: "Estación 05", position: "Ascensor" },
    { id: "m12", no: 12, location: "Estación 06", position: "General" },
    { id: "m13", no: 13, location: "Estación 07", position: "Ascensor" },
    { id: "m14", no: 14, location: "Estación 07", position: "Escalera" },
    { id: "m15", no: 15, location: "Transuix 201", position: "Área Transuix" },
    { id: "m16", no: 16, location: "Transuix 209", position: "Área Transuix" },
    { id: "m17", no: 17, location: "Transuix 08", position: "Área Transuix" },
    { id: "m18", no: 18, location: "El Hoyo", position: "Sector El Hoyo" },
    { id: "m19", no: 19, location: "Entrada Don Jaime", position: "Acceso / Entrada" },
    { id: "m20", no: 20, location: "Patio Taller Comedor", position: "Patio Taller / Comedor" },
    { id: "m21", no: 21, location: "Para Rayo 01", position: "Protección / Para Rayos" },
    { id: "m22", no: 22, location: "Para Rayo 02", position: "Protección / Para Rayos" },
    { id: "m23", no: 23, location: "Lote 08", position: "Área Lote" },
    { id: "m24", no: 24, location: "Ruta Motorizada", position: "Motorizada 01" },
    { id: "m25", no: 25, location: "Ruta Motorizada", position: "Motorizada 02" },
    { id: "m26", no: 26, location: "Ruta Motorizada", position: "Motorizada 03" },
    { id: "m27", no: 27, location: "Estación 12", position: "Escalera" },
    { id: "m28", no: 28, location: "Estación 12", position: "Ascensor" },
  ],
  /** Personal base turno diurno (AM) — se importa a empleados como "(Monorriel)" */
  staffAm: [
    "HECTOR LOPEZ",
    "JIMMY DE AZA",
    "ROBERTO FERREIRA",
    "MANUEL PEÑA",
    "FERNANDO CONTRERA",
    "FELIX MARIA ESTEVEZ",
    "TEODORO PEÑA",
    "SANTOS SANTOS AYBAR",
    "OSIRIS CONTRERA",
    "BENITO RAMIREZ",
    "JOSE MIGUEL ABREU",
    "FAUSTO MARTINEZ",
    "MARIANO BURGOS",
    "FELLO GARCIA",
    "ENMANUEL MARTINEZ",
    "GILBERTO GARCIA",
    "ODANNY GARCIA",
    "FERNANDO SANTOS",
    "MARIO PEÑA",
    "ALEXIS PERALTA",
    "NARCISO ESTRELLA",
    "DANIEL PEREZ DIAZ",
    "LINO ANTONIO FERNANDEZ",
    "JORGE TEJADA",
    "JUNIOR TAVAREZ",
    "ROBERTICO DIAZ",
  ],
  /** Personal base turno nocturno (PM) */
  staffPm: [
    "FRANCISCO MERAN",
    "ANEUDY GARCIA",
    "ROMAN ROSARIO",
    "RAMON UREÑA",
    "JUAN BAEZ",
    "FRANCISCO CARRASCO",
    "FRANCISCO ANTONIO CERDA",
    "CARLOS PERALTA",
    "FERNANDO PIERRE",
    "JOSE RAMON RODRIGUEZ",
    "ANTONIO ROSSIS",
    "ROBINSON JOSUE LOPEZ",
    "MIGUEL ALEJANDRO",
    "JESUS MARIA MATA",
    "JEUDY RODRIGUEZ",
    "MANUEL LORENZO",
    "ANSELMO REYES",
    "FRANCISCO LUCIANO CONTRERA",
    "WILLIAM RODRIGUEZ",
    "HENYORI POLANCO",
    "WILLY ESTEVEZ",
    "CRIS ANDERSON",
  ],
};
